### ISSUE TITLE
Tarod crash if .taro folder exists

### ISSUE THREAD

**Issue by vafanassieff** [lightninglabs/taproot-assets#175]
Running `tarod version 0.1.0-alpha commit=v0.1.0-alpha-50-g556d3ae`

If the folder `~/.taro` already exist, tarod crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x11a830e]

goroutine 1 [running]:
github.com/lightninglabs/taro/tarocfg.LoadConfig({0xc00008b080, 0xc0000949c0, 0xc000094a20, 0xc000094a80, {0x0}})
  /go/src/github.com/lightningnetwork/taro/tarocfg/config.go:340 +0xa4e
main.main()
  /go/src/github.com/lightningnetwork/taro/cmd/tarod/main.go:25 +0x11e
```

**Comment by jharveyb** [comment]
Should be resolved with 0.3.
