### ISSUE TITLE
[itest flake]: taro daemon sometimes doesn't start in itest

### ISSUE THREAD

**Issue by guggero** [lightninglabs/taproot-assets#192]
```
2022-11-10 15:09:30.077 [INF] CONF: Opening sqlite3 database at: /tmp/itest-tarod2976623735/data/regtest/taro.db
panic: Fail in goroutine after TestTaroDaemon/full_value_send has completed

goroutine 4034 [running]:
testing.(*common).Fail(0xc001294340)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:817 +0xe5
testing.(*common).FailNow(0xc001294340)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:840 +0x2c
testing.(*common).Fatalf(0xc001294340, {0x166b7db?, 0x1?}, {0xc00035df48?, 0x1?, 0xc000100a80?})
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:948 +0x65
github.com/lightninglabs/taro/itest.(*harnessTest).Fatalf(0xc000092f00, {0x1669518?, 0x18?}, {0xc00035dfc0?, 0x1?, 0x1?})
	/home/runner/work/taro/taro/itest/test_harness.go:130 +0x1ae
github.com/lightninglabs/taro/itest.(*tarodHarness).start.func2()
	/home/runner/work/taro/taro/itest/tarod_harness.go:128 +0x6c
created by github.com/lightninglabs/taro/itest.(*tarodHarness).start
	/home/runner/work/taro/taro/itest/tarod_harness.go:125 +0x25f
FAIL	github.com/lightninglabs/taro/itest	29.449s
```

**Comment by Roasbeef** [comment]
Closing as fixed.
