### ISSUE TITLE
[bug]: Mom error when synching universe with proof_type=transfer

### ISSUE THREAD

**Issue by snow884** [lightninglabs/taproot-assets#593]
### Background

Describe your issue here.

### Your environment

```
$tapcli getinfo                                   
{
    "version": "0.3.0-alpha.rc2 commit=v0.3.0-alpha.rc2-2-ge695071",
    "lnd_version": "0.16.99-beta",
    "network": "testnet3"
}

$uname -mrsv
Linux 6.1.29-50.88.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jun  6 00:47:06 UTC 2023 x86_64

$bitcoind --version
Bitcoin Core version v22.0.0
```

### Steps to reproduce

Run universe synch with proof_type=transfer

```
tapcli universe sync --universe_host universe.tiramisuwallet.com:10029 --asset_id=35b559df8a67ddfced7ad7a242bc70ba303a1d3dbbe7756b942a9ed7050132cd --proof_type=transfer
```

### Expected behavior

Successful sync.

### Actual behavior

Got an error from the tapd:
```
2023-10-17 16:07:01.018 [INF] UNIV: Root for issuance-35b559df8a67ddfced7ad7a242bc70ba303a1d3dbbe7756b942a9ed7050132cd matches, no sync needed
2023-10-17 16:07:01.899 [INF] UNIV: Attempting to sync universe: host=universe.tiramisuwallet.com:10029, sync_type=issuance, ids=([]universe.Identifier) (len=1 cap=1) {
 (universe.Identifier) issuance-35b559df8a67ddfced7ad7a242bc70ba303a1d3dbbe7756b942a9ed7050132cd
}

2023-10-17 16:07:01.900 [INF] UNIV: Fetching 1 roots
2023-10-17 16:07:01.905 [INF] UNIV: Obtained 1 roots from remote Universe server
2023-10-17 16:07:01.905 [DBG] UNIV: Looking up root node for base Universe (universe.Identifier) issuance-35b559df8a67ddfced7ad7a242bc70ba303a1d3dbbe7756b942a9ed7050132cd

2023-10-17 16:07:01.905 [INF] UNIV: Root for issuance-35b559df8a67ddfced7ad7a242bc70ba303a1d3dbbe7756b942a9ed7050132cd matches, no sync needed
2023-10-17 16:07:44.491 [INF] UNIV: Attempting to sync universe: host=universe.tiramisuwallet.com:10029, sync_type=issuance, ids=([]universe.Identifier) (len=1 cap=1) {
 (universe.Identifier) transfer-35b559df8a67ddfced7ad7a242bc70ba303a1d3dbbe7756b942a9ed7050132cd
}

2023-10-17 16:07:44.492 [INF] UNIV: Fetching 1 roots
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x139f3fd]

goroutine 79007 [running]:
github.com/lightninglabs/taproot-assets.UnmarshalUniID(0x0)
        /home/ec2-user/taproot-assets/rpcserver.go:2782 +0x3d
github.com/lightninglabs/taproot-assets.unmarshalUniverseRoot(0xc0043978b0)
        /home/ec2-user/taproot-assets/universe_rpc_diff.go:47 +0x7a
github.com/lightninglabs/taproot-assets.(*RpcUniverseDiff).RootNode(0xc000cfd640, {0x1b79250, 0xc0044ec500}, {{0x35, 0xb5, 0x59, 0xdf, 0x8a, 0x67, 0xdd, ...}, ...})
        /home/ec2-user/taproot-assets/universe_rpc_diff.go:115 +0x1e7
github.com/lightninglabs/taproot-assets/universe.(*SimpleSyncer).executeSync.func2({0x1b79250?, 0xc0044ec500?}, {{0x35, 0xb5, 0x59, 0xdf, 0x8a, 0x67, 0xdd, 0xfc, ...}, ...})
        /home/ec2-user/taproot-assets/universe/syncer.go:94 +0xa8
github.com/lightninglabs/taproot-assets/fn.ParSlice[...].func1()
        /home/ec2-user/taproot-assets/fn/concurrency.go:29 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/ec2-user/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 79001
        /home/ec2-user/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0x96
```

**Comment by guggero** [comment]
Thanks for the report. I added a fix that should avoid the panic. Though the question here is: Why was the message nil in the first place?
Is the node running at `universe.tiramisuwallet.com` upgraded to `v0.3.0-alpha.rc2` as well? And started from a fresh/clean database?
